variable "deployment_project_id" {
  type     = string
  description = "The ID of a GCP project that will be generated."
}

variable "deployment_project_name" {
  type     = string
  description = "The name of a GCP project that will be generated."
}

variable "deployment_project_folder_id" {
  type     = string
  description = "The ID of a GCP project folder, in which to create a generated GCP project."
}

variable "deployment_project_labels" {
  type     = map(string)
  nullable = false
  default  = {}

  description = "Optional labels to apply to the GCP project"
}

variable "create_projects" {
  type    = bool
  default = true
  description = "Whether to create the projects in this module or not"
}

variable "deployment_project_billing_account" {
  type     = string
  nullable = true
  default  = null

  description = "The GCP billing account to use for the generated project."
}

variable "compute_project_id" {
  type     = string
  default  = null
  nullable = true

  description = "The ID of the GCP project used for executing pipeline tasks. This project is not generated by this script unless it is set to the deployment_project_id (the default)."
}

variable "billing_project_id" {
  type     = string
  default  = null
  nullable = true

  description = "The ID of the GCP project used for billing. This project is not generated by this script unless it is set to the deployment_project_id (the default)."
}

variable "region" {
  type    = string
  default = "us-central1"
  validation {
    condition = contains([
      "us-central1", "us-west2", "northamerica-northeast1", "europe-west2", "europe-west4", "asia-southeast1",
      "asia-southeast2"
    ], var.region)
    error_message = "Region must be one of: us-central1, us-west2, northamerica-northeast1, europe-west2, europe-west4, asia-southeast1, asia-southeast2"
  }

  description = "The GCP region in which to deploy Cromwell and where pipeline jobs are executed."
}

variable "zone" {
  type    = string
  default = "us-central1-c"

  description = "The GCP zone to use for the Cromwell deployment and any associated zonal resources."
}

variable "db_tier" {
  type    = string
  default = "db-f1-micro"

  description = "The tier of database instance to use for Cromwell's MySQL database."
}

variable "credential_version" {
  type    = number
  default = 1

  description = "A variable to force generated database credentials to rotate."
}

variable "allow_deletion" {
  type    = bool
  default = false

  description = "Set this to true in order to allow destroying stateful resources (buckets, DBs, etc.)"
}

variable "cromwell_version" {
  type     = string
  nullable = false
  default  = 85

  description = "Set the version of Cromwell to install"
}

variable "additional_buckets" {
  description = "Additional buckets to add to the policy"
  type = list(object({
    name    = string
    project = string
  }))
  default = []
  nullable = true
}

variable "cromwell_sql_maintenance_window_day" {
  description = "The day of week (1-7), starting on Monday for the maintenance window"
  type        = number
  default     = 1
}

variable "cromwell_sql_maintenance_window_hour" {
  description = "The hour of day (0-23), ignored if day not set for the maintenance window (UTC)"
  type        = number
}

variable "cromwell_sql_database_version" {
  description = "Database version to use for the Cromwell SQL database"
  type     = string
  default     = "MYSQL_8_0"
}
